# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MovieTrending' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieTrending
  pod 'Cosmos'
  pod 'TinyConstraints'

  target 'MovieTrendingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieTrendingUITests' do
    # Pods for testing
  end

end
